### ISSUE TITLE
Element is not defined when integrate with sendbird-uikit

### ISSUE THREAD

**Issue by xhygithub** [sendbird/SendBird-UIKIT-JavaScript#4]
We have followed the instruction to install the sendbird-uikit and use the components the sendbird-uikit provides. But it throws the error: "**ReferenceError: Element is not defined**"

The following is my code:
//Sendbird
```
import React, { useState } from 'react';
import Chat from './Chat';

const Sendbird: React.FC<{}> = () => {
  return (
    <div className="App">
      <Chat userId="1234" nickname="sendbird" theme="light" />
    </div>
  );
};

export default Sendbird;
```

//chat
```
import React, { FC, useState } from 'react';
import { App as SendBirdApp } from 'sendbird-uikit';
export default function Chat({ userId, nickname, theme }) {
  const APP_ID = 'D6E16xxxxxx';
  return (
    <div style={{ height: '100vh' }}>
      <SendBirdApp
          appId={APP_ID}
          userId={userId}
          nickname={nickname}
      />
    </div>
  );
}

```
My sendbird-uikit version in package.json is    **"sendbird-uikit": "1.0.0"**

When running the app, it throws:
```
[2020-05-07T07:17:06.611Z] ERROR: web/WebPlugin/72253 on local: Element is not defined (appName=opus)
    ReferenceError: Element is not defined
        at Object.<anonymous> (/Users/xxxx/node_modules/sendbird-uikit/src/ui/ContextMenu/index.jsx:161:53)
        at Module._compile (internal/modules/cjs/loader.js:1158:30)
        at Module._compile (/Users/xxx/node_modules/ts-node-dev/node_modules/source-map-support/source-map-support.js:541:25)
        at Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
        at require.extensions..js (/private/var/folders/ng/nk2n7v8172v5lsly71jrylp40000gn/T/ts-node-dev-hook-9354307550712957.js:95:14)
        at Object.nodeDevHook [as .js] (/Users/xxx/node_modules/ts-node-dev/lib/hook.js:61:7)
        at Module.load (internal/modules/cjs/loader.js:1002:32)
        at Function.Module._load (internal/modules/cjs/loader.js:901:14)
        at Module.require (internal/modules/cjs/loader.js:1044:19)
        at require (internal/modules/cjs/helpers.js:77:18)
        at eval (webpack:///external_%22sendbird-uikit%22?:1:18)
        at Object.sendbird-uikit (/Users/xxx/dist/s.js:19404:1)
        at __webpack_require__ (/Users/xxx/dist/s.js:21:30)
        at eval (webpack:///./app/pages/Sendbird/Chat.tsx?:10:22)
        at Object../app/pages/Sendbird/Chat.tsx (/Users/xxx/dist/s.js:16111:1)
        at __webpack_require__ (/Users/xxx/dist/s.js:21:30)

```

**Comment by xhygithub** [comment]
Using https://loadable-components.com/docs/server-side-rendering/ for the server side rendering in my application. I saw in the sendbird-uikit source code, there is a comment **might fail on server side render**. I am not sure if it is the root cause, anyone has solution?

**Comment by sravan-s** [comment]
Hi @xhygithub can you send a minimum reproducible codesandbox or repo?

**Comment by xhygithub** [comment]
@sravan-s https://codesandbox.io/s/cocky-platform-302fu?file=/pages/index.js

**Comment by sravan-s** [comment]
Thanks

**Comment by sravan-s** [comment]
Hello,

So, the idea is that for SSR, there are some hurdles that we have to handle
• Unlike other components, chat is not a static component, so we have to fetch data on each load
• For that, SDK need to smart about what kind of websocket/http connection the server uses, which is not possible the moment

The solution at the moment is to hydrate the chat once it is in client

Almost all good libraries have the same concept, in nextjs it can be found in this link ->  https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr

 
https://codesandbox.io/s/cocky-hawking-h3zbs

**Comment by sravan-s** [comment]
p.s. I will update docs.sendbird.com with this information

**Comment by xhygithub** [comment]
thanks for your help @sravan-s . It works well
